import { FLAGS } from './data/flags.js';
import type { FlagFormat, ResolvedProfileConfig } from './types.js';

function quote(value: string): string {
  return JSON.stringify(value);
}

export function createTypeScriptManifest(profile: ResolvedProfileConfig): string {
  const flags = profile.countries.map((code) => `  ${code}: ${quote(FLAGS[code])},`).join('\n');
  const sizes = profile.sizes.map(([width, height]) => `${width}x${height}`);
  const sizeValues = sizes.map((size) => `  ${quote(size)},`).join('\n');
  const dimensions = profile.sizes
    .map(
      ([width, height]) =>
        `  ${quote(`${width}x${height}`)}: { width: ${width}, height: ${height} },`,
    )
    .join('\n');
  const formats = profile.formats.map((format) => `  ${quote(format)},`).join('\n');
  const publicPaths = profile.formats
    .map((format: FlagFormat) => {
      const output = profile.output[format];
      if (!output) throw new Error(`Missing resolved output for ${format}.`);
      return `  ${format}: ${quote(output.publicPath)},`;
    })
    .join('\n');

  return `// Generated by @celtian/flag-resizer. Do not edit.

export const FLAGS = {
${flags}
} as const;

export type CountryCode = keyof typeof FLAGS;

export const FLAG_SIZES = [
${sizeValues}
] as const;

export type FlagSize = (typeof FLAG_SIZES)[number];

export const FLAG_DIMENSIONS = {
${dimensions}
} as const satisfies Record<FlagSize, { width: number; height: number }>;

export const FLAG_FORMATS = [
${formats}
] as const;

export type FlagFormat = (typeof FLAG_FORMATS)[number];

export const FLAG_PUBLIC_PATHS = {
${publicPaths}
} as const satisfies Record<FlagFormat, string>;

export function getFlagPath(
  code: CountryCode,
  size: FlagSize,
  format: FlagFormat,
): string {
  const publicPath = FLAG_PUBLIC_PATHS[format];
  const basePath = publicPath === '/' ? '' : publicPath;
  return \`\${basePath}/\${size}/\${code}.\${format}\`;
}
`;
}
